name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        mruby_version: [2.1.2]
        experimental:  [false]
        include:
        - mruby_version: 3.0.0-preview
          experimental: true

    runs-on: ubuntu-18.04
    # see misc/. TODO: introduce independent repo
    container: docker.io/udzura/mruby-seccomp-base:20201203

    steps:
    - uses: actions/checkout@v2
    - name: Packages
      run: sudo apt-get -y -qq install curl
    - name: Run Build
      env:
        MRUBY_VERSION: ${{ matrix.mruby_version }}
      continue-on-error: ${{ matrix.experimental }}
      run: rake test