name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        mruby_version: [2.1.2]
        libseccomp_version: [2.3.1, 2.5.1]
        experimental:  [false]
        include:
        - mruby_version: 3.0.0-preview
          libseccomp_version: 2.5.1
          experimental: true

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build a Container
      run: |
        docker build -t haconiwa/mruby-seccomp misc/
    - name: Run Build and Test
      run: |
        /bin/bash -c \
                   "docker run --privileged \
                   --pid=host \
                   -v $(pwd):/mruby-seccomp \
                   -e MRUBY_VERSION=${{ matrix.mruby_version }} \
                   -e MEB_SECCOMP_LIBVER=${{ matrix.libseccomp_version }} \
                   haconiwa/mruby-seccomp \
                   /bin/bash -c 'cd /mruby-seccomp && rake test'"
      continue-on-error: ${{ matrix.experimental }}
